
server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
    
  thymeleaf:
    prefix: "classpath:templates/"
    suffix: .html

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: web-study.cq7w8v7xxjsd.ap-northeast-2.rds.amazonaws.com:3306/G-OSK
    username: admin
    password: 1q2w3e4r

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/G-OSK/upload/
